/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package br.com.ft6;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Operacao extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1872093538057433886L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Operacao\",\"namespace\":\"br.com.ft6\",\"fields\":[{\"name\":\"operacao_origem\",\"type\":\"string\"},{\"name\":\"topico_destino\",\"type\":\"string\"},{\"name\":\"payload\",\"type\":{\"type\":\"map\",\"values\":\"string\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Operacao> ENCODER =
      new BinaryMessageEncoder<Operacao>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Operacao> DECODER =
      new BinaryMessageDecoder<Operacao>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Operacao> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Operacao> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Operacao> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Operacao>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Operacao to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Operacao from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Operacao instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Operacao fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence operacao_origem;
   private java.lang.CharSequence topico_destino;
   private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> payload;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Operacao() {}

  /**
   * All-args constructor.
   * @param operacao_origem The new value for operacao_origem
   * @param topico_destino The new value for topico_destino
   * @param payload The new value for payload
   */
  public Operacao(java.lang.CharSequence operacao_origem, java.lang.CharSequence topico_destino, java.util.Map<java.lang.CharSequence,java.lang.CharSequence> payload) {
    this.operacao_origem = operacao_origem;
    this.topico_destino = topico_destino;
    this.payload = payload;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return operacao_origem;
    case 1: return topico_destino;
    case 2: return payload;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: operacao_origem = (java.lang.CharSequence)value$; break;
    case 1: topico_destino = (java.lang.CharSequence)value$; break;
    case 2: payload = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'operacao_origem' field.
   * @return The value of the 'operacao_origem' field.
   */
  public java.lang.CharSequence getOperacaoOrigem() {
    return operacao_origem;
  }


  /**
   * Sets the value of the 'operacao_origem' field.
   * @param value the value to set.
   */
  public void setOperacaoOrigem(java.lang.CharSequence value) {
    this.operacao_origem = value;
  }

  /**
   * Gets the value of the 'topico_destino' field.
   * @return The value of the 'topico_destino' field.
   */
  public java.lang.CharSequence getTopicoDestino() {
    return topico_destino;
  }


  /**
   * Sets the value of the 'topico_destino' field.
   * @param value the value to set.
   */
  public void setTopicoDestino(java.lang.CharSequence value) {
    this.topico_destino = value;
  }

  /**
   * Gets the value of the 'payload' field.
   * @return The value of the 'payload' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getPayload() {
    return payload;
  }


  /**
   * Sets the value of the 'payload' field.
   * @param value the value to set.
   */
  public void setPayload(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
    this.payload = value;
  }

  /**
   * Creates a new Operacao RecordBuilder.
   * @return A new Operacao RecordBuilder
   */
  public static br.com.ft6.Operacao.Builder newBuilder() {
    return new br.com.ft6.Operacao.Builder();
  }

  /**
   * Creates a new Operacao RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Operacao RecordBuilder
   */
  public static br.com.ft6.Operacao.Builder newBuilder(br.com.ft6.Operacao.Builder other) {
    if (other == null) {
      return new br.com.ft6.Operacao.Builder();
    } else {
      return new br.com.ft6.Operacao.Builder(other);
    }
  }

  /**
   * Creates a new Operacao RecordBuilder by copying an existing Operacao instance.
   * @param other The existing instance to copy.
   * @return A new Operacao RecordBuilder
   */
  public static br.com.ft6.Operacao.Builder newBuilder(br.com.ft6.Operacao other) {
    if (other == null) {
      return new br.com.ft6.Operacao.Builder();
    } else {
      return new br.com.ft6.Operacao.Builder(other);
    }
  }

  /**
   * RecordBuilder for Operacao instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Operacao>
    implements org.apache.avro.data.RecordBuilder<Operacao> {

    private java.lang.CharSequence operacao_origem;
    private java.lang.CharSequence topico_destino;
    private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> payload;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(br.com.ft6.Operacao.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.operacao_origem)) {
        this.operacao_origem = data().deepCopy(fields()[0].schema(), other.operacao_origem);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.topico_destino)) {
        this.topico_destino = data().deepCopy(fields()[1].schema(), other.topico_destino);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.payload)) {
        this.payload = data().deepCopy(fields()[2].schema(), other.payload);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Operacao instance
     * @param other The existing instance to copy.
     */
    private Builder(br.com.ft6.Operacao other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.operacao_origem)) {
        this.operacao_origem = data().deepCopy(fields()[0].schema(), other.operacao_origem);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.topico_destino)) {
        this.topico_destino = data().deepCopy(fields()[1].schema(), other.topico_destino);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.payload)) {
        this.payload = data().deepCopy(fields()[2].schema(), other.payload);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'operacao_origem' field.
      * @return The value.
      */
    public java.lang.CharSequence getOperacaoOrigem() {
      return operacao_origem;
    }


    /**
      * Sets the value of the 'operacao_origem' field.
      * @param value The value of 'operacao_origem'.
      * @return This builder.
      */
    public br.com.ft6.Operacao.Builder setOperacaoOrigem(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.operacao_origem = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'operacao_origem' field has been set.
      * @return True if the 'operacao_origem' field has been set, false otherwise.
      */
    public boolean hasOperacaoOrigem() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'operacao_origem' field.
      * @return This builder.
      */
    public br.com.ft6.Operacao.Builder clearOperacaoOrigem() {
      operacao_origem = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'topico_destino' field.
      * @return The value.
      */
    public java.lang.CharSequence getTopicoDestino() {
      return topico_destino;
    }


    /**
      * Sets the value of the 'topico_destino' field.
      * @param value The value of 'topico_destino'.
      * @return This builder.
      */
    public br.com.ft6.Operacao.Builder setTopicoDestino(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.topico_destino = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'topico_destino' field has been set.
      * @return True if the 'topico_destino' field has been set, false otherwise.
      */
    public boolean hasTopicoDestino() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'topico_destino' field.
      * @return This builder.
      */
    public br.com.ft6.Operacao.Builder clearTopicoDestino() {
      topico_destino = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'payload' field.
      * @return The value.
      */
    public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getPayload() {
      return payload;
    }


    /**
      * Sets the value of the 'payload' field.
      * @param value The value of 'payload'.
      * @return This builder.
      */
    public br.com.ft6.Operacao.Builder setPayload(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
      validate(fields()[2], value);
      this.payload = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'payload' field has been set.
      * @return True if the 'payload' field has been set, false otherwise.
      */
    public boolean hasPayload() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'payload' field.
      * @return This builder.
      */
    public br.com.ft6.Operacao.Builder clearPayload() {
      payload = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Operacao build() {
      try {
        Operacao record = new Operacao();
        record.operacao_origem = fieldSetFlags()[0] ? this.operacao_origem : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.topico_destino = fieldSetFlags()[1] ? this.topico_destino : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.payload = fieldSetFlags()[2] ? this.payload : (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Operacao>
    WRITER$ = (org.apache.avro.io.DatumWriter<Operacao>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Operacao>
    READER$ = (org.apache.avro.io.DatumReader<Operacao>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.operacao_origem);

    out.writeString(this.topico_destino);

    long size0 = this.payload.size();
    out.writeMapStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.util.Map.Entry<java.lang.CharSequence, java.lang.CharSequence> e0: this.payload.entrySet()) {
      actualSize0++;
      out.startItem();
      out.writeString(e0.getKey());
      java.lang.CharSequence v0 = e0.getValue();
      out.writeString(v0);
    }
    out.writeMapEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Map-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.operacao_origem = in.readString(this.operacao_origem instanceof Utf8 ? (Utf8)this.operacao_origem : null);

      this.topico_destino = in.readString(this.topico_destino instanceof Utf8 ? (Utf8)this.topico_destino : null);

      long size0 = in.readMapStart();
      java.util.Map<java.lang.CharSequence,java.lang.CharSequence> m0 = this.payload; // Need fresh name due to limitation of macro system
      if (m0 == null) {
        m0 = new java.util.HashMap<java.lang.CharSequence,java.lang.CharSequence>((int)size0);
        this.payload = m0;
      } else m0.clear();
      for ( ; 0 < size0; size0 = in.mapNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.CharSequence k0 = null;
          k0 = in.readString(k0 instanceof Utf8 ? (Utf8)k0 : null);
          java.lang.CharSequence v0 = null;
          v0 = in.readString(v0 instanceof Utf8 ? (Utf8)v0 : null);
          m0.put(k0, v0);
        }
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.operacao_origem = in.readString(this.operacao_origem instanceof Utf8 ? (Utf8)this.operacao_origem : null);
          break;

        case 1:
          this.topico_destino = in.readString(this.topico_destino instanceof Utf8 ? (Utf8)this.topico_destino : null);
          break;

        case 2:
          long size0 = in.readMapStart();
          java.util.Map<java.lang.CharSequence,java.lang.CharSequence> m0 = this.payload; // Need fresh name due to limitation of macro system
          if (m0 == null) {
            m0 = new java.util.HashMap<java.lang.CharSequence,java.lang.CharSequence>((int)size0);
            this.payload = m0;
          } else m0.clear();
          for ( ; 0 < size0; size0 = in.mapNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.CharSequence k0 = null;
              k0 = in.readString(k0 instanceof Utf8 ? (Utf8)k0 : null);
              java.lang.CharSequence v0 = null;
              v0 = in.readString(v0 instanceof Utf8 ? (Utf8)v0 : null);
              m0.put(k0, v0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










